couchbase:
  image: couch_base
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210
  volumes_from:
    - linking_volume_couchbase
  environment:
    BUCKET: sync_gateway
    CB_USER: Administrator
    CB_PASS: password

couchdb:
  image: couchdb_config
  ports:
    - 5984:5984
  links:
    - couchbase
 #   - sync_gateway
    
sync_gateway:
  image: sync_gateway
  ports:
    - 4984:4984
    - 4985:4985
  links:
    - couchbase